### PR TITLE
feat: Tester subcommands

### PR DESCRIPTION
**Pull request by e4r7hbug**
Provide some help with checking a Spinnaker setup from the Foremast perspective. This should provide a nicer way of seeing which Foremast configurations are not set properly. Also, this could help with detecting if components of Spinnaker are down.

Depends on: #86

``` bash
$ foremast tester -h
No configuration found in the following locations:

/etc/foremast/foremast.cfg
/home/ntangsurat/.foremast/foremast.cfg
./.foremast/foremast.cfg

Section missing from configurations: [base]
[base] missing key "gate_api_url", using None.
[base] missing key "git_url", using None.
[base] missing key "domain", using 'example.com'.
[base] missing key "envs", using ''.
[base] missing key "regions", using ''.
[base] missing key "types", using 'ec2,lambda'.
[base] missing key "templates_path", using None.
[base] missing key "ami_json_url", using None.
[base] missing key "default_ec2_securitygroups", using ''.
[base] missing key "default_elb_securitygroups", using ''.
Section missing from configurations: [credentials]
[credentials] missing key "gitlab_token", using None.
[credentials] missing key "slack_token", using None.
Section missing from configurations: [whitelists]
[whitelists] missing key "asg_whitelist", using ''.
[base] missing key "gate_client_cert", using ''.
[base] missing key "gate_ca_bundle", using ''.
usage: foremast tester [-h] {all,gate} ...

optional arguments:
  -h, --help  show this help message and exit

Testers:
  {all,gate}
    all       Run all tests. Args: args (CliArgs): Arguments from CLI.
    gate      Check Gate connection.
```

### CODE REVIEW

**Comment by sijis** [comment]
Is the idea to add other components/checks to this in the future besides gate?

I'm on the fence about this and maybe its because its called a 'Tester'.
I think in reality this is a 'Credential' or 'Connectivity' validator.

**Comment by e4r7hbug** [comment]
Yeah, the idea would be to check if `foremast` can reach out to the different Spinnaker components. Should help clarify if your configuration is correct. Hm…I wouldn't be opposed to change the command name.

**Comment by sijis** [comment]
@e4r7hbug I think 'Validate' could be the better name.
Eventually we could add a config validator among other minor things. I'm visualizing the use as
`$ foremast validate config`

@ndcampbell thoughts?

**Comment by e4r7hbug** [comment]
`validate` makes sense. So…now we should probably change things to consistently say `validate` instead of `validator`. Because every time I type "validator", there's a red squiggly.

**Comment by sijis** [comment]
I made the suggested changes.

**Comment by e4r7hbug** [comment]
Good stuffs.

**Pull request merged**
