### PR TITLE
feat: Add ability to use a dynamic config

### PR DESCRIPTION
**Pull request by sijis**
We are now able to load a python file 'config.py' as a source of
configuration details.

### CODE REVIEW

**Comment by sijis** [comment]
This add basic functionality and it essentially assumes that `config.py` is in the same directory that foremast is executed.

If this is eventually merged, I think we should also consider adding deprecation notice regarding `foremast.cfg` and eventually drop it in the next major release.

**Comment by sijis** [comment]
Oh yeah, here's an example config.py
```
CONFIG = {

    'base': {
        'domain': 'example.com',
        'envs': 'dev,stage',
        'regions': 'us-east-1,us-west-2',
        'git_url': 'https://github.com',
        'gate_api_url': 'https://example.com:1234',
        'templates_path': '/path/to/github/foremast-templates',
        'default_ec2_securitygroups': 'my_office',
        'default_elb_securitygroups': 'all_apps',
        'gate_client_cert': '/path/to/my.pem',
        'gate_ca_bundle': '/path/to/bundle.pem',
        'types': 'ec2,lambda,manual',
    },
    'credentials': {
        'gitlab_token': 'yyyyyyyyyyyyyyyyyyyyyy',
        'slack_token': 'zzzzzzzzzzzzzzzzzzzzzzz',
    },

    'whitelists': {
        'asg_whitelist': 'myspecial_app',
    },

    'formats': {
        'domain': 'example.com',
    }
}
```

**Comment by ndcampbell** [comment]
I really like this. It makes it so we can use Vault (or any source of secrets) for the tokens and SSL certs.

**Comment by ndcampbell** [comment]
I see no issues with the code and I think it can be merged in since old static functionality is maintained.

**Pull request merged**
