### PR TITLE
fix: Manual pipeline safe name

### PR DESCRIPTION
**Pull request by e4r7hbug**
Need to remove bad characters from the generated Pipeline name in accordance with Spinnaker's name checker. This allows manual Pipelines to be created and deleted properly.

### CODE REVIEW

**Comment by sijis** [comment]
This needs a simple test for the normalized function.

**Comment by e4r7hbug** [comment]
Test case added.

**Comment by sijis** [comment]
👍 I'm good with this.

**Comment by e4r7hbug** [comment]
Turns out, updating an existing Pipeline without deleting it is fairly trivial with all our existing functions.

**Comment by sijis** [comment]
I would have moved the pipeline removal to a separate PR. It may be trivial but I would like more eyes on that specific change.

**Comment by e4r7hbug** [comment]
Split Pipeline deletion related Commits to #110.

**Comment by sijis** [comment]
Thanks for breaking that up into 2 parts.

**Pull request merged**
