### PR TITLE
updated to use region specific configs

### PR DESCRIPTION
**Pull request by ndcampbell**
Updates the datapipeline, DNS, S3, Security Groups, and ELB services in Foremast to use region specific configs

### CODE REVIEW

**Comment by ndcampbell** [comment]
@sijis updated to update all Foremast services except Pipeline creation since that will be done a bit differently and require some more testing

**Comment by sijis** [comment]
@ndcampbell Could you please rebase this branch with `master`?
There were changes merged in Friday afternoon.
I want to ensure there are no issues.

**Comment by ndcampbell** [comment]
@sijis rebased

**Comment by sijis** [comment]
Thanks. I'm not seeing any problems with this.

**Pull request merged**
