### PR TITLE
feat: Provide centralized Git file retrieval

### PR DESCRIPTION
**Pull request by e4r7hbug**
Manual Pipelines will need to retrieve Pipeline JSON definition files from Git. This provides a concise way to grab the file and will be useful for refactoring `process_git_configs()` in [src/foremast/configs/prepare_configs.py](https://github.com/gogoair/foremast/blob/master/src/foremast/configs/prepare_configs.py).

See also: #72

### CODE REVIEW

**Comment by ndcampbell** [comment]
Should https://github.com/gogoair/foremast/blob/master/src/foremast/configs/prepare_configs.py#L32 be updated in this commit then to use the new util or do it in a different PR?

Also, will manual pipelines still allow passing in a "runway_dir" for the configuration? I don't want a hard gitlab dependency.

**Comment by e4r7hbug** [comment]
I want to get the code into place first, then update the other code.

You're right about the `runway_dir`. I'll add support for that.

**Comment by ndcampbell** [comment]
I think it should be generalized if it is not only using Git.

**Comment by e4r7hbug** [comment]
Okay. I think this thing is done. Anyone want to give it one more look over?

**Comment by sijis** [comment]
I'm merging this as its a precursor to other pending PRs.

**Pull request merged**
