### PR TITLE
Stage asg

### PR DESCRIPTION
**Pull request by bazimov**
Set minimum default restriction for stage environment

### CODE REVIEW

**Comment by sijis** [comment]
I'm really against this.
We should have a different mechanism to incorporate things like this, like a plugin.

**Comment by jvasallo** [comment]
We need to remember that this library is a shared library by the world. We cannot impose limits on our end users (specifically over Spinnaker). Fully agree with @sijis on this one.

**Comment by e4r7hbug** [comment]
Do you guys have an example that can help Bek go in the right direction?

**Comment by e4r7hbug** [comment]
We've had some side discussions. Please change this to add `ASG_WHITELIST` to `data` that is passed into the Template. This will then enable template logic like:
```python
"min": {%- if data.app.appname not in data.ASG_WHITELIST %} 10 {% else %} {{ data.asg.min_inst }} {%- endif %},
```

**Comment by e4r7hbug** [comment]
Will resolve #95.

**Comment by e4r7hbug** [comment]
This still needs to pass `ASG_WHITELIST` into the `data` dictionary.

**Comment by bazimov** [comment]
@e4r7hbug ASG_WHITELIST is in consts.py, not used in the construct_pipeline_block.py.

**Comment by e4r7hbug** [comment]
Please refer to your diff.

**Comment by ndcampbell** [comment]
I think this looks good to me. Have our internal templates been updated yet?

**Comment by bazimov** [comment]
I am updating the internal templates soon.

**Pull request merged**
