### PR TITLE
feat: Unified CLI commands

### PR DESCRIPTION
**Pull request by e4r7hbug**
This provides a more explorable CLI structure. Try to ignore the configuration spew for now, we'll need to clean up the side effect of importing `foremast.consts` eventually.

``` bash
$ foremast
No configuration found in the following locations:

/etc/foremast/foremast.cfg
/home/ntangsurat/.foremast/foremast.cfg
./.foremast/foremast.cfg

Section missing from configurations: [base]
[base] missing key "gate_api_url", using None.
[base] missing key "git_url", using None.
[base] missing key "domain", using 'example.com'.
[base] missing key "envs", using ''.
[base] missing key "regions", using ''.
[base] missing key "types", using 'ec2,lambda'.
[base] missing key "templates_path", using None.
[base] missing key "ami_json_url", using None.
[base] missing key "default_ec2_securitygroups", using ''.
[base] missing key "default_elb_securitygroups", using ''.
Section missing from configurations: [credentials]
[credentials] missing key "gitlab_token", using None.
[credentials] missing key "slack_token", using None.
Section missing from configurations: [whitelists]
[whitelists] missing key "asg_whitelist", using ''.
[base] missing key "gate_client_cert", using ''.
[base] missing key "gate_ca_bundle", using ''.
usage: foremast [-h] [-d] [-s] {infra,pipeline,rebuild,autoscaling} ...

Foremast, your ship's support.

optional arguments:
  -h, --help            show this help message and exit
  -d, --debug           Set DEBUG output (default: 20)
  -s, --short-log       Truncated logging format (default: %(asctime)s
                        [%(levelname)s] %(name)s:%(funcName)s:%(lineno)d -
                        %(message)s)

Commands:
  Available activies

  {infra,pipeline,rebuild,autoscaling}
    infra               Entry point for preparing the infrastructure in a
                        specific env.
    pipeline            Pipeline subcommands.
    rebuild             Entry point for rebuilding pipelines. Use to rebuild
                        all pipelines or a specific group.
    autoscaling         Create Auto Scaling Policy for an Auto Scaling Group.
```

### CODE REVIEW

**Comment by sijis** [comment]
@e4r7hbug If we merge this, will we have to update all our commands or will the 'old way' still work?

**Comment by e4r7hbug** [comment]
Older command will remain untouched and fully functional.

**Comment by sijis** [comment]
:+1: I see no issues with this.

**Comment by ndcampbell** [comment]
This looks good to me too. Can it be merged in?

**Pull request merged**
